---
name: iOS CI (Build & TestFlight)

'on':
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - run: gem install fastlane

      - name: Install provisioning profile
        env:
          MOBILEPROVISION_BASE64: ${{ secrets.IOS_MOBILEPROVISION_BASE64 }}
        run: |
          PROFILES_DIR=~/Library/MobileDevice/Provisioning\ Profiles
          mkdir -p "$PROFILES_DIR"
          echo "$MOBILEPROVISION_BASE64" | base64 --decode > \
            "$PROFILES_DIR/build_pp.mobileprovision"

      - name: Build archive
        run: |
          xcodebuild -scheme "GPU-Terminal" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/App.xcarchive \
            clean archive \
            CODE_SIGNING_ALLOWED=YES

      - name: Export IPA
        run: |
          cat > exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key><string>app-store</string>
              <key>stripSwiftSymbols</key><true/>
              <key>teamID</key><string>YOUR_TEAM_ID</string>
            </dict>
          </plist>
          PLIST
          xcodebuild -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist exportOptions.plist

      - name: Upload to TestFlight
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8_BASE64: ${{ secrets.ASC_KEY_P8_BASE64 }}
        run: |
          echo "$ASC_KEY_P8_BASE64" | base64 --decode > AuthKey.p8
          API_KEY_JSON="{\"key_id\":\"$ASC_KEY_ID\",\"issuer_id\":\"$ASC_ISSUER_ID\",\"key_filepath\":\"AuthKey.p8\"}"
          fastlane pilot upload \
            --api_key "$API_KEY_JSON" \
            --ipa ./build/*.ipa \
            --skip_waiting_for_build_processing true
