---
name: iOS CI (Build & TestFlight)

'on':
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - run: gem install fastlane
      - name: Build archive
        run: |
          if ! ls *.xcodeproj 1>/dev/null 2>&1 && \
             ! ls *.xcworkspace 1>/dev/null 2>&1 && \
             [ ! -f Package.swift ]; then
            echo "Missing Xcode project, workspace, or Package.swift." >&2
            exit 1
          fi
          xcodebuild -scheme "GPU-Terminal" \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            -archivePath $PWD/build/App.xcarchive \
            clean archive
      - name: Package IPA
        run: |
          ditto -c -k --sequesterRsrc --keepParent \
            $PWD/build/App.xcarchive/Products/Applications/*.app \
            $PWD/build/App.ipa

      - name: Upload to TestFlight
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8_BASE64: ${{ secrets.ASC_KEY_P8_BASE64 }}
        run: |
          echo "$ASC_KEY_P8_BASE64" | base64 --decode > AuthKey.p8
          API_KEY_JSON="{\"key_id\":\"$ASC_KEY_ID\",\"issuer_id\":\"$ASC_ISSUER_ID\",\"key_filepath\":\"AuthKey.p8\"}"
          fastlane pilot upload \
            --api_key "$API_KEY_JSON" \
            --ipa ./build/*.ipa \
            --skip_waiting_for_build_processing true
